package me.rhunk.snapenhance.common.config.impl

import me.rhunk.snapenhance.common.config.ConfigContainer

class AmoledThemeConfig : ConfigContainer(hasGlobalState = true) {
    val sigColorTextPrimary = boolean("sigColorTextPrimary", true)
    val sigColorBackgroundSurface = boolean("sigColorBackgroundSurface", true)
    val sigColorBackgroundMain = boolean("sigColorBackgroundMain", true)
    val actionSheetBackgroundDrawable = boolean("actionSheetBackgroundDrawable", true)
    val actionSheetRoundedBackgroundDrawable = boolean("actionSheetRoundedBackgroundDrawable", true)
    val sigColorChatChat = boolean("sigColorChatChat", true)
    val sigColorChatPendingSending = boolean("sigColorChatPendingSending", true)
    val sigColorChatSnapWithSound = boolean("sigColorChatSnapWithSound", true)
    val sigColorChatSnapWithoutSound = boolean("sigColorChatSnapWithoutSound", true)
    val sigExceptionColorCameraGridLines = boolean("sigExceptionColorCameraGridLines", true)
    val listDivider = boolean("listDivider", true)
    val listBackgroundDrawable = boolean("listBackgroundDrawable", true)
    val sigColorIconPrimary = boolean("sigColorIconPrimary", true)
    val actionSheetDescriptionTextColor = boolean("actionSheetDescriptionTextColor", true)
    val ringColor = boolean("ringColor", true)
    val sigColorIconSecondary = boolean("sigColorIconSecondary", true)
    val itemShapeFillColor = boolean("itemShapeFillColor", true)
    val ringStartColor = boolean("ringStartColor", true)
    val sigColorLayoutPlaceholder = boolean("sigColorLayoutPlaceholder", true)
    val scButtonColor = boolean("scButtonColor", true)
    val recipientPillBackgroundDrawable = boolean("recipientPillBackgroundDrawable", true)
    val boxBackgroundColor = boolean("boxBackgroundColor", true)
    val editTextColor = boolean("editTextColor", true)
    val chipBackgroundColor = boolean("chipBackgroundColor", true)
    val recipientInputStyle = boolean("recipientInputStyle", true)
    val rangeFillColor = boolean("rangeFillColor", true)
    val pstsIndicatorColor = boolean("pstsIndicatorColor", true)
    val pstsTabBackground = boolean("pstsTabBackground", true)
    val pstsDividerColor = boolean("pstsDividerColor", true)
    val tabTextColor = boolean("tabTextColor", true)
    val statusBarForeground = boolean("statusBarForeground", true)
    val statusBarBackground = boolean("statusBarBackground", true)
    val strokeColor = boolean("strokeColor", true)
    val storyReplayViewRingColor = boolean("storyReplayViewRingColor", true)
    val sigColorButtonPrimary = boolean("sigColorButtonPrimary", true)
    val sigColorBaseAppYellow = boolean("sigColorBaseAppYellow", true)
    val sigColorBackgroundSurfaceTranslucent = boolean("sigColorBackgroundSurfaceTranslucent", true)
    val sigColorStoryRingFriendsFeedStoryRing = boolean("sigColorStoryRingFriendsFeedStoryRing", true)
    val sigColorStoryRingDiscoverTabThumbnailStoryRing = boolean("sigColorStoryRingDiscoverTabThumbnailStoryRing", true)
}
