name: Generate Keystore

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  generate_key:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '11' # Or your required Java version
        distribution: 'temurin'

    - name: Generate Keystore
      run: |
        keytool -genkeypair \
          -alias purfectsnap \
          -keyalg RSA \
          -keysize 2048 \
          -keystore purfectsnap.jks \
          -storepass ${{ secrets.KEYSTORE_PASSWORD }} \
          -keypass ${{ secrets.KEY_PASSWORD }} \
          -dname "CN=My App, OU=My Org, O=My Company, L=City, ST=State, C=Country" \
          -validity 3650 # Validity in days

    - name: Upload Keystore as Artifact (Optional)
      uses: actions/upload-artifact@v4
      with:
        name: myapp-keystore
        path: myapp.jks
